# Playbook to do basic VM cloning from snapshots and powering on
- name: ML Failover Playbook 
  hosts: all
  connection: ansible.builtin.local
  gather_facts: false

  environment: 
    SC_HOST: "https://{{ inventory_hostname }}"
    SC_USERNAME: "{{ scale_user }}"
    SC_PASSWORD: "{{ scale_pass }}"
# Tasks
  tasks:
# Clone from most recent snap
    - name: Create from most recent snap of VM "Portainer1"
      scale_computing.hypercore.vm_clone:
        vm_name: VDI-Clone1
        source_vm_name: Win11-Template
      register: result
# Power on the VM
    - name: Power on the VM
      scale_computing.hypercore.vm_params:
        vm_name: VDI-Clone1
        power_state: start
      register: result
