- name: ML Failover Playbook 
  hosts: all
  connection: ansible.builtin.local
  gather_facts: false

  environment: 
    SC_HOST: "https://{{ inventory_hostname }}"
    SC_USERNAME: "{{ scale_user }}""
    SC_PASSWORD: "{{ scale_pass }}"

  tasks:
    - name: Create from most recent snap named "Portainer-DR" from VM "Portainer1"
      scale_computing.hypercore.vm_snapshot:
        vm_name: Portainer1
        label: Portainer1-clone
        state: present
  register: vm_snapshot
