---
- name: Check if 
  hosts: localhost
  gather_facts: no
  vars:
    websites:
      - apal.example.com:port
      - intranet.inventory.db:port
    email_recipient: "your_email@example.com"
    email_subject: "Unable to Reach Port"
    email_body: ""
  tasks:
    - name: Test Websites
      ansible.builtin.uri:
        url: "https://{{ item }}"
        return_content: no
        status_code: 200
      register: result
      with_items: "{{ websites }}"
      ignore_errors: yes

    - name: Gather failed targets and response times
      set_fact:
        down_websites: "{{ down_websites | default([]) + [{'site': item.item, 'elapsed': item.elapsed}] }}"
      when: item.status != 200
      with_items: "{{ result.results }}"

    - name: Set email body if any service is down
      set_fact:
        email_body: >
          The following services are not responding:
          {% for site in down_websites %}
          - {{ site.site }} (Response time: {{ site.elapsed }} ms)
          {% endfor %}
      when: down_websites is defined and down_websites | length > 0

    - name: Send email if any service is down
      ansible.builtin.mail:
        host: "73.103.52.91"
        port: 25
        to: "{{ email_recipient }}"
        subject: "{{ email_subject }}"
        body: "{{ email_body }}"
      when: down_websites is defined and down_websites | length > 0
