- name: AAP Failover Playbook 
  hosts: all
  connection: ansible.builtin.local
  gather_facts: false

  environment: 
    SC_HOST: "https://{{ inventory_hostname }}"
    SC_USERNAME: "{{ scale_user }}""
    SC_PASSWORD: "{{ scale_pass }}"

  tasks:
    - name: Create from most recent snap named "APAL-DR" from VM "2012vm-clone"
      scale_computing.hypercore.vm_snapshot:
        vm_name: 2012vm-clone
        label: new
        state: present
  register: vm_snapshot
